[phases.setup]
nixPkgs = ["python311", "postgresql", "redis", "stdenv.cc"]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[phases.setup.env]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_NO_CACHE_DIR = "1"
LD_LIBRARY_PATH = "/nix/store/ybjcla5bhj8g1y84998pn4a2drfxybkv-gcc-13.3.0-lib/lib:/nix/store/bzk3q2l71qwhycsip23y6rl5n881la4n-zlib-1.3.1/lib"
