# Generated by Django 4.2.7 on 2026-02-18 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('views_velocity', models.FloatField(default=0.0)),
                ('likes_velocity', models.FloatField(default=0.0)),
                ('comments_velocity', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('prediction_score', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('trend_period', models.IntegerField(default=24)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('page_visited', models.URLField()),
                ('time_on_page', models.PositiveIntegerField(default=0)),
                ('entry_point', models.URLField(blank=True)),
                ('exit_point', models.BooleanField(default=False)),
                ('conversion_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='analytics_u_session_30d6ff_idx'), models.Index(fields=['user', 'created_at'], name='analytics_u_user_id_536f15_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('time_on_page', models.PositiveIntegerField(default=0)),
                ('scroll_depth', models.FloatField(default=0.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_708804_idx'), models.Index(fields=['article', 'action_type'], name='analytics_u_article_39cbfc_idx'), models.Index(fields=['timestamp'], name='analytics_u_timesta_cfbd6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_articles_read', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('average_reading_speed', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('preferred_reading_time', models.CharField(blank=True, choices=[('morning', 'Morning (6AM-12PM)'), ('afternoon', 'Afternoon (12PM-6PM)'), ('evening', 'Evening (6PM-12AM)'), ('night', 'Night (12AM-6AM)')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ContentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_views', models.PositiveIntegerField(default=0)),
                ('daily_likes', models.PositiveIntegerField(default=0)),
                ('daily_comments', models.PositiveIntegerField(default=0)),
                ('daily_shares', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_time_on_page', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('article', 'date')},
            },
        ),
    ]
