# Generated by Django 4.2.7 on 2026-02-18 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_vector', models.JSONField(default=dict)),
                ('tag_vector', models.JSONField(default=dict)),
                ('reading_time_preference', models.FloatField(default=0.0)),
                ('complexity_preference', models.FloatField(default=0.0)),
                ('update_frequency', models.IntegerField(default=24)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('recommendation_type', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based'), ('trending', 'Trending'), ('similar_users', 'Similar Users'), ('category_based', 'Category-Based')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='TrendingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField()),
                ('predicted_score', models.FloatField(default=0.0)),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('actual_score', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('features_used', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('clicked', 'Clicked'), ('liked', 'Liked'), ('bookmarked', 'Bookmarked'), ('shared', 'Shared'), ('not_interested', 'Not Interested'), ('hide', 'Hide Recommendation')], max_length=20)),
                ('feedback_value', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.userrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vector', models.JSONField(default=dict)),
                ('category_vector', models.JSONField(default=dict)),
                ('tag_vector', models.JSONField(default=dict)),
                ('length_score', models.FloatField(default=0.0)),
                ('complexity_score', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('similarity_type', models.CharField(choices=[('content', 'Content-Based'), ('tags', 'Tags-Based'), ('category', 'Category-Based'), ('user_behavior', 'User Behavior')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_1', to='articles.article')),
                ('article2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_2', to='articles.article')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', '-score'], name='recommendat_user_id_469d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['created_at'], name='recommendat_created_0720a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrecommendation',
            unique_together={('user', 'article')},
        ),
        migrations.AddIndex(
            model_name='trendingprediction',
            index=models.Index(fields=['article', '-prediction_date'], name='recommendat_article_16ca65_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingprediction',
            index=models.Index(fields=['-predicted_score'], name='recommendat_predict_bb126c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['user', 'feedback_type'], name='recommendat_user_id_0c6bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['article', 'feedback_type'], name='recommendat_article_f258ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlesimilarity',
            unique_together={('article1', 'article2', 'similarity_type')},
        ),
    ]
